---
language: python
python: "3.9"
sudo: required
services:
  - docker
install:
  - pip install pipenv
  - pipenv sync
env:
  matrix:
    - MOLECULE_DISTRO=debian:buster-slim REDIS_VERSION=5.0.5
    - MOLECULE_DISTRO=debian:stretch-slim REDIS_VERSION=5.0.5
    - MOLECULE_DISTRO=debian:jessie-slim REDIS_VERSION=5.0.5
    - MOLECULE_DISTRO=debian:buster-slim REDIS_VERSION=4.0.14 REDIS_CLUSTER_LEGACY=true REDIS_RUBY_GEM=4.1.3
    - MOLECULE_DISTRO=debian:stretch-slim REDIS_VERSION=4.0.14 REDIS_CLUSTER_LEGACY=true REDIS_RUBY_GEM=4.1.3
    - MOLECULE_DISTRO=debian:jessie-slim REDIS_VERSION=4.0.14 REDIS_CLUSTER_LEGACY=true REDIS_RUBY_GEM=3.3.5
    - MOLECULE_DISTRO=debian:buster-slim REDIS_VERSION=3.2.13 REDIS_CLUSTER_LEGACY=true REDIS_RUBY_GEM=3.3.5
    - MOLECULE_DISTRO=debian:stretch-slim REDIS_VERSION=3.2.13 REDIS_CLUSTER_LEGACY=true REDIS_RUBY_GEM=3.3.5
    - MOLECULE_DISTRO=debian:jessie-slim REDIS_VERSION=3.2.13 REDIS_CLUSTER_LEGACY=true REDIS_RUBY_GEM=3.3.5
script:
  - travis_wait 30 pipenv run molecule test -s single
  - travis_wait 30 pipenv run molecule test -s cluster

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
