---
dist: focal
language: python
os: linux
sudo: required
services:
  - docker
before_install:
  - echo '{"default-cgroupns-mode":"host"}' | sudo tee /etc/docker/daemon.json
  - sudo systemctl restart docker

jobs:
  include:
  - &ansible-2.9
    python: 3.8
    install:
      - pip install pipenv
      - rm Pipfile
      - pipenv install -r test-requirements-python-2.9.txt --skip-lock
    env:
      - MOLECULE_DISTRO=debian:bookworm-slim REDIS_VERSION=8.2.2
  - <<: *ansible-2.9
    env:
      - MOLECULE_DISTRO=debian:bullseye-slim REDIS_VERSION=8.2.2
  - <<: *ansible-2.9
    env:
      - MOLECULE_DISTRO=debian:buster-slim REDIS_VERSION=8.2.2
  - <<: *ansible-2.9
    env:
      - MOLECULE_DISTRO=debian:stretch-slim REDIS_VERSION=8.2.2
  - &ansible-5.0.1
    python: 3.8
    install:
      - pip install -I pipenv
      - pipenv sync
    env:
      - MOLECULE_DISTRO=debian:bookworm-slim REDIS_VERSION=8.2.2
  - <<: *ansible-5.0.1
    env:
      - MOLECULE_DISTRO=debian:bullseye-slim REDIS_VERSION=8.2.2
  - <<: *ansible-5.0.1
    env:
      - MOLECULE_DISTRO=debian:buster-slim REDIS_VERSION=8.2.2
  - <<: *ansible-5.0.1
    env:
      - MOLECULE_DISTRO=debian:stretch-slim REDIS_VERSION=8.2.2
script:
  - travis_wait 3 pipenv run molecule test -s single
  - travis_wait 3 pipenv run molecule test -s cluster

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    if: branch = main
    on_success: change
    on_failure: always
    recipients:
      - desarrollo.benders@idealista.com