---
language: python
python: "3.9"
sudo: required
services:
  - docker
install:
  - pip install -I pipenv
  - pipenv sync
env:
  matrix:
    - MOLECULE_DISTRO=debian:bullseye-slim REDIS_VERSION=7.2.3
    - MOLECULE_DISTRO=debian:buster-slim REDIS_VERSION=7.2.3
    - MOLECULE_DISTRO=debian:stretch-slim REDIS_VERSION=7.2.3
script:
  - travis_wait 30 pipenv run molecule test -s single
  - travis_wait 30 pipenv run molecule test -s cluster

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
