---

- name: restart redis
  ansible.builtin.service:
    name: redis-server
    state: restarted

  when: redis_service_state != 'stopped'

- name: oneshot disable thp
  ansible.builtin.systemd:
    name: disable_thp
    state: restarted
