---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - &redis-anchor
    name: rediscluster1
    groups:
      - redis
    image: ${MOLECULE_DISTRO:-debian:bullseye-slim}
    dockerfile: ../common/Dockerfile.j2
    hostname: rediscluster1
    privileged: false
    capabilities:
      - SYS_ADMIN
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:rw'
      - '/var/run/docker.sock:/var/run/docker.sock'
    cgroupns_mode: host
    tmpfs:
      - /redis
      - /tmp
      - /run
      - /run/lock
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: "redis-cluster-network"
  - <<: *redis-anchor
    name: rediscluster2
  - <<: *redis-anchor
    name: rediscluster3
  - <<: *redis-anchor
    name: rediscluster4
  - <<: *redis-anchor
    name: rediscluster5
  - <<: *redis-anchor
    name: rediscluster6

provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: "${MOLECULE_SCENARIO_DIRECTORY}/vault.pw"
  inventory:
    group_vars:
      redis:
        redis_version: ${REDIS_VERSION:-"7.2.3"}
        redis_cluster_legacy: ${REDIS_CLUSTER_LEGACY:-false}
        redis_ruby_gem_version: ${REDIS_RUBY_GEM:-4.1.3}
scenario:
  name: cluster
verifier:
  name: ansible
